[Core]
Name = slack_client
Module = slack_client

[Documentation]
Author = Nick Driver
Version = 1.0
Description = Interact with Slack Workspaces

[options]
# Slackbot Auth Token
token = <your-slackbot-token>

# Slackbot admin channel
admin_channel = mojo-admin

# SLackbot user channel
user_channel = mojo

# SlackUserID for your SlackBot
user_id = U0000000000