services:
  ledmgmt:
    build:
      context: .
      dockerfile: ledhntr.Dockerfile
    image: ledmgmt
    volumes:
      - ./ledhntr.cfg:/home/leduser/.ledhntr/ledhntr.cfg
    ports:
      - '5001:5001'
    # user: 'leduser'
  typedb:
    image: vaticle/typedb:2.21.0
    platform: linux/amd64
    volumes:
      - typedb-data:/opt/typedb-all-linux/server/data/
    ports:
      - '1729:1729'

volumes:
  typedb-data: