services:
  typedb:
    image: vaticle/typedb:2.28.3
    container_name: typedb
    platform: linux/amd64
    volumes:
      - typedb_opt:/opt/
      - typedb_data:/opt/typedb-all-linux-x86_64/server/data
    ports:
      - '1729:1729'
    networks:
      - led_dbnet
    restart: unless-stopped

  ledapi-redis-stack:
    image: redis/redis-stack:7.4.0-rc1-x86_64
    container_name: ledapi-redis-stack
    platform: linux/amd64
    volumes:
      - ledapi_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - led_dbnet
    restart: unless-stopped

  ledapi-container:
    build:
      context: .
      dockerfile: ledapi.Dockerfile
      args:
        # typedb_client is required by default, but you can list other plugins
        # you want to install here in a space-delimited manner
        PLUGINS: "shodan censys"
    image: ledapi-app
    container_name: ledapi-container
    volumes:
      - ledapi_data:/ledhntr
      - ledapi_ledhntr_data:/home/leduser/.ledhntr
      - ledapi_dev_home:/home/leduser/
    ports:
      - "8000:8000"
    networks:
      - led_dbnet
      - led_apinet
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:latest
    container_name: led-nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - led_dmz
      - led_apinet

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=<your_cloudflare_tunnel_token>
    networks:
      - led_dmz

volumes:
  typedb_opt:
    external: true
  typedb_data:
    external: true
  ledapi_redis_data:
    external: true
  ledapi_data:
    external: true
  ledapi_ledhntr_data:
    external: true
  ledapi_dev_home:

networks:
  led_dmz:
  led_apinet:
  led_dbnet:
